/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CorporatesBody1
 */

public class CorporatesBody1 {
  @JsonProperty("sourceOfFundsOther")
  private String sourceOfFundsOther = null;

  @JsonProperty("companyType")
  private String companyType = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("mobile")
  private Mobile mobile = null;

  @JsonProperty("industry")
  private Object industry = null;

  @JsonProperty("sourceOfFunds")
  private Object sourceOfFunds = null;

  @JsonProperty("companyBusinessAddress")
  private Object companyBusinessAddress = null;

  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("feeGroup")
  private String feeGroup = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("baseCurrency")
  private String baseCurrency = null;

  public CorporatesBody1 sourceOfFundsOther(String sourceOfFundsOther) {
    this.sourceOfFundsOther = sourceOfFundsOther;
    return this;
  }

   /**
   * Description of source of funds in case &#x60;OTHER&#x60; was chosen.
   * @return sourceOfFundsOther
  **/
  public String getSourceOfFundsOther() {
    return sourceOfFundsOther;
  }

  public void setSourceOfFundsOther(String sourceOfFundsOther) {
    this.sourceOfFundsOther = sourceOfFundsOther;
  }

  public CorporatesBody1 companyType(String companyType) {
    this.companyType = companyType;
    return this;
  }

   /**
   * Get companyType
   * @return companyType
  **/
  public String getCompanyType() {
    return companyType;
  }

  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }

  public CorporatesBody1 surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * The last name of the Corporate root user.
   * @return surname
  **/
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public CorporatesBody1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The first name of the Corporate root user.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CorporatesBody1 mobile(Mobile mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  public Mobile getMobile() {
    return mobile;
  }

  public void setMobile(Mobile mobile) {
    this.mobile = mobile;
  }

  public CorporatesBody1 industry(Object industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  public Object getIndustry() {
    return industry;
  }

  public void setIndustry(Object industry) {
    this.industry = industry;
  }

  public CorporatesBody1 sourceOfFunds(Object sourceOfFunds) {
    this.sourceOfFunds = sourceOfFunds;
    return this;
  }

   /**
   * Get sourceOfFunds
   * @return sourceOfFunds
  **/
  public Object getSourceOfFunds() {
    return sourceOfFunds;
  }

  public void setSourceOfFunds(Object sourceOfFunds) {
    this.sourceOfFunds = sourceOfFunds;
  }

  public CorporatesBody1 companyBusinessAddress(Object companyBusinessAddress) {
    this.companyBusinessAddress = companyBusinessAddress;
    return this;
  }

   /**
   * Get companyBusinessAddress
   * @return companyBusinessAddress
  **/
  public Object getCompanyBusinessAddress() {
    return companyBusinessAddress;
  }

  public void setCompanyBusinessAddress(Object companyBusinessAddress) {
    this.companyBusinessAddress = companyBusinessAddress;
  }

  public CorporatesBody1 tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * A field for custom tags linked to this corporate.
   * @return tag
  **/
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public CorporatesBody1 feeGroup(String feeGroup) {
    this.feeGroup = feeGroup;
    return this;
  }

   /**
   * The fee group which the Corporate will be bound to. Do not specify this if you are not using fee groups.
   * @return feeGroup
  **/
  public String getFeeGroup() {
    return feeGroup;
  }

  public void setFeeGroup(String feeGroup) {
    this.feeGroup = feeGroup;
  }

  public CorporatesBody1 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email address of the Corporate root user.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CorporatesBody1 baseCurrency(String baseCurrency) {
    this.baseCurrency = baseCurrency;
    return this;
  }

   /**
   * The default currency of the corporate.
   * @return baseCurrency
  **/
  public String getBaseCurrency() {
    return baseCurrency;
  }

  public void setBaseCurrency(String baseCurrency) {
    this.baseCurrency = baseCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorporatesBody1 corporates_body_1 = (CorporatesBody1) o;
    return Objects.equals(this.sourceOfFundsOther, corporates_body_1.sourceOfFundsOther) &&
        Objects.equals(this.companyType, corporates_body_1.companyType) &&
        Objects.equals(this.surname, corporates_body_1.surname) &&
        Objects.equals(this.name, corporates_body_1.name) &&
        Objects.equals(this.mobile, corporates_body_1.mobile) &&
        Objects.equals(this.industry, corporates_body_1.industry) &&
        Objects.equals(this.sourceOfFunds, corporates_body_1.sourceOfFunds) &&
        Objects.equals(this.companyBusinessAddress, corporates_body_1.companyBusinessAddress) &&
        Objects.equals(this.tag, corporates_body_1.tag) &&
        Objects.equals(this.feeGroup, corporates_body_1.feeGroup) &&
        Objects.equals(this.email, corporates_body_1.email) &&
        Objects.equals(this.baseCurrency, corporates_body_1.baseCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceOfFundsOther, companyType, surname, name, mobile, industry, sourceOfFunds, companyBusinessAddress, tag, feeGroup, email, baseCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorporatesBody1 {\n");
    
    sb.append("    sourceOfFundsOther: ").append(toIndentedString(sourceOfFundsOther)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    sourceOfFunds: ").append(toIndentedString(sourceOfFunds)).append("\n");
    sb.append("    companyBusinessAddress: ").append(toIndentedString(companyBusinessAddress)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    feeGroup: ").append(toIndentedString(feeGroup)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    baseCurrency: ").append(toIndentedString(baseCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
