/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20013
 */

public class InlineResponse20013 {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("responseCount")
  private Integer responseCount = null;

  @JsonProperty("accounts")
  private List<ManagedAccount> accounts = null;

  public InlineResponse20013 count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * The total number of records (excluding the paging limit).
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public InlineResponse20013 responseCount(Integer responseCount) {
    this.responseCount = responseCount;
    return this;
  }

   /**
   * The total number of records returned in this response (always capped at 100).
   * @return responseCount
  **/
  public Integer getResponseCount() {
    return responseCount;
  }

  public void setResponseCount(Integer responseCount) {
    this.responseCount = responseCount;
  }

  public InlineResponse20013 accounts(List<ManagedAccount> accounts) {
    this.accounts = accounts;
    return this;
  }

  public InlineResponse20013 addAccountsItem(ManagedAccount accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * The filtered managed accounts list.
   * @return accounts
  **/
  public List<ManagedAccount> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<ManagedAccount> accounts) {
    this.accounts = accounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20013 inline_response_200_13 = (InlineResponse20013) o;
    return Objects.equals(this.count, inline_response_200_13.count) &&
        Objects.equals(this.responseCount, inline_response_200_13.responseCount) &&
        Objects.equals(this.accounts, inline_response_200_13.accounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, responseCount, accounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20013 {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    responseCount: ").append(toIndentedString(responseCount)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
