/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2008
 */

public class InlineResponse2008 {
  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("responseCount")
  private Integer responseCount = null;

  @JsonProperty("send")
  private List<Send> send = null;

  public InlineResponse2008 count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Total number of records (excluding the paging limit).
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public InlineResponse2008 responseCount(Integer responseCount) {
    this.responseCount = responseCount;
    return this;
  }

   /**
   * Total number of records returned in this response.
   * @return responseCount
  **/
  public Integer getResponseCount() {
    return responseCount;
  }

  public void setResponseCount(Integer responseCount) {
    this.responseCount = responseCount;
  }

  public InlineResponse2008 send(List<Send> send) {
    this.send = send;
    return this;
  }

  public InlineResponse2008 addSendItem(Send sendItem) {
    if (this.send == null) {
      this.send = new ArrayList<>();
    }
    this.send.add(sendItem);
    return this;
  }

   /**
   * Get send
   * @return send
  **/
  public List<Send> getSend() {
    return send;
  }

  public void setSend(List<Send> send) {
    this.send = send;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inline_response_200_8 = (InlineResponse2008) o;
    return Objects.equals(this.count, inline_response_200_8.count) &&
        Objects.equals(this.responseCount, inline_response_200_8.responseCount) &&
        Objects.equals(this.send, inline_response_200_8.send);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, responseCount, send);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    responseCount: ").append(toIndentedString(responseCount)).append("\n");
    sb.append("    send: ").append(toIndentedString(send)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
