/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse2004
 */

public class InlineResponse2004 {
  /**
   * The status of the Due Diligence for the consumer.
   */
  public enum FullDueDiligenceEnum {
    NOT_STARTED("NOT_STARTED"),
    INITIATED("INITIATED"),
    PENDING_REVIEW("PENDING_REVIEW"),
    APPROVED("APPROVED"),
    REJECTED("REJECTED");

    private String value;

    FullDueDiligenceEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FullDueDiligenceEnum fromValue(String input) {
      for (FullDueDiligenceEnum b : FullDueDiligenceEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("fullDueDiligence")
  private FullDueDiligenceEnum fullDueDiligence = null;

  public InlineResponse2004 fullDueDiligence(FullDueDiligenceEnum fullDueDiligence) {
    this.fullDueDiligence = fullDueDiligence;
    return this;
  }

   /**
   * The status of the Due Diligence for the consumer.
   * @return fullDueDiligence
  **/
  public FullDueDiligenceEnum getFullDueDiligence() {
    return fullDueDiligence;
  }

  public void setFullDueDiligence(FullDueDiligenceEnum fullDueDiligence) {
    this.fullDueDiligence = fullDueDiligence;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inline_response_200_4 = (InlineResponse2004) o;
    return Objects.equals(this.fullDueDiligence, inline_response_200_4.fullDueDiligence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullDueDiligence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    fullDueDiligence: ").append(toIndentedString(fullDueDiligence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
