/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * InlineResponse40938
 */

public class InlineResponse40938 {
  /**
   * Gets or Sets errorCode
   */
  public enum ErrorCodeEnum {
    INSTRUMENT_ALREADY_UPGRADED_TO_PHYSICAL("INSTRUMENT_ALREADY_UPGRADED_TO_PHYSICAL"),
    CONFIG_ERROR_PRODUCT_REFERENCE("CONFIG_ERROR_PRODUCT_REFERENCE"),
    PRODUCT_REFERENCE_NOT_SPECIFIED("PRODUCT_REFERENCE_NOT_SPECIFIED"),
    PRODUCT_REFERENCE_INVALID("PRODUCT_REFERENCE_INVALID"),
    CONFIG_ERROR_CARRIER_TYPE("CONFIG_ERROR_CARRIER_TYPE"),
    CARRIER_TYPE_NOT_SPECIFIED("CARRIER_TYPE_NOT_SPECIFIED"),
    CARRIER_TYPE_INVALID("CARRIER_TYPE_INVALID"),
    CONFIG_ERROR_CARD_BUREAU("CONFIG_ERROR_CARD_BUREAU"),
    INSTRUMENT_BLOCKED("INSTRUMENT_BLOCKED"),
    INSTRUMENT_DESTROYED("INSTRUMENT_DESTROYED"),
    PIN_INVALID_FORMAT("PIN_INVALID_FORMAT"),
    PARENT_MANAGED_ACCOUNT_BLOCKED("PARENT_MANAGED_ACCOUNT_BLOCKED");

    private String value;

    ErrorCodeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ErrorCodeEnum fromValue(String input) {
      for (ErrorCodeEnum b : ErrorCodeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("errorCode")
  private ErrorCodeEnum errorCode = null;

  public InlineResponse40938 errorCode(ErrorCodeEnum errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public ErrorCodeEnum getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(ErrorCodeEnum errorCode) {
    this.errorCode = errorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse40938 inline_response_409_38 = (InlineResponse40938) o;
    return Objects.equals(this.errorCode, inline_response_409_38.errorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse40938 {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
