/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ManagedCardsAssignBody
 */

public class ManagedCardsAssignBody {
  @JsonProperty("externalReference")
  private String externalReference = null;

  @JsonProperty("nameOnCard")
  private String nameOnCard = null;

  @JsonProperty("activationCode")
  private String activationCode = null;

  @JsonProperty("billingAddress")
  private Object billingAddress = null;

  @JsonProperty("friendlyName")
  private String friendlyName = null;

  @JsonProperty("cardholderMobileNumber")
  private String cardholderMobileNumber = null;

  public ManagedCardsAssignBody externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Unique code identifying a card.
   * @return externalReference
  **/
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public ManagedCardsAssignBody nameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
    return this;
  }

   /**
   * The name that will be printed on the card.
   * @return nameOnCard
  **/
  public String getNameOnCard() {
    return nameOnCard;
  }

  public void setNameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
  }

  public ManagedCardsAssignBody activationCode(String activationCode) {
    this.activationCode = activationCode;
    return this;
  }

   /**
   * The code to be used to activate the physical card. Depending on how the cards were created, this may be a code set upon creation, or it may be the same as the &#x60;externalReference&#x60;.
   * @return activationCode
  **/
  public String getActivationCode() {
    return activationCode;
  }

  public void setActivationCode(String activationCode) {
    this.activationCode = activationCode;
  }

  public ManagedCardsAssignBody billingAddress(Object billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  public Object getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(Object billingAddress) {
    this.billingAddress = billingAddress;
  }

  public ManagedCardsAssignBody friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

   /**
   * The friendly name given to the card.
   * @return friendlyName
  **/
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public ManagedCardsAssignBody cardholderMobileNumber(String cardholderMobileNumber) {
    this.cardholderMobileNumber = cardholderMobileNumber;
    return this;
  }

   /**
   * The mobile number including country code of the card holder, needed for 3DS challenge.
   * @return cardholderMobileNumber
  **/
  public String getCardholderMobileNumber() {
    return cardholderMobileNumber;
  }

  public void setCardholderMobileNumber(String cardholderMobileNumber) {
    this.cardholderMobileNumber = cardholderMobileNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedCardsAssignBody managed_cards_assign_body = (ManagedCardsAssignBody) o;
    return Objects.equals(this.externalReference, managed_cards_assign_body.externalReference) &&
        Objects.equals(this.nameOnCard, managed_cards_assign_body.nameOnCard) &&
        Objects.equals(this.activationCode, managed_cards_assign_body.activationCode) &&
        Objects.equals(this.billingAddress, managed_cards_assign_body.billingAddress) &&
        Objects.equals(this.friendlyName, managed_cards_assign_body.friendlyName) &&
        Objects.equals(this.cardholderMobileNumber, managed_cards_assign_body.cardholderMobileNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalReference, nameOnCard, activationCode, billingAddress, friendlyName, cardholderMobileNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedCardsAssignBody {\n");
    
    sb.append("    externalReference: ").append(toIndentedString(externalReference)).append("\n");
    sb.append("    nameOnCard: ").append(toIndentedString(nameOnCard)).append("\n");
    sb.append("    activationCode: ").append(toIndentedString(activationCode)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    cardholderMobileNumber: ").append(toIndentedString(cardholderMobileNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
