/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * StatementEntry
 */

public class StatementEntry {
  @JsonProperty("originalAmount")
  private CurrencyAmount originalAmount = null;

  @JsonProperty("forexRate")
  private ScaledAmount forexRate = null;

  @JsonProperty("additionalFields")
  private Map<String, String> additionalFields = null;

  @JsonProperty("cardholderFee")
  private CurrencyAmount cardholderFee = null;

  @JsonProperty("transactionAmount")
  private CurrencyAmount transactionAmount = null;

  @JsonProperty("processedTimestamp")
  private Long processedTimestamp = null;

  @JsonProperty("balanceAfter")
  private CurrencyAmount balanceAfter = null;

  @JsonProperty("sourceAmount")
  private Object sourceAmount = null;

  @JsonProperty("transactionId")
  private TransactionId transactionId = null;

  public StatementEntry originalAmount(CurrencyAmount originalAmount) {
    this.originalAmount = originalAmount;
    return this;
  }

   /**
   * Get originalAmount
   * @return originalAmount
  **/
  public CurrencyAmount getOriginalAmount() {
    return originalAmount;
  }

  public void setOriginalAmount(CurrencyAmount originalAmount) {
    this.originalAmount = originalAmount;
  }

  public StatementEntry forexRate(ScaledAmount forexRate) {
    this.forexRate = forexRate;
    return this;
  }

   /**
   * Get forexRate
   * @return forexRate
  **/
  public ScaledAmount getForexRate() {
    return forexRate;
  }

  public void setForexRate(ScaledAmount forexRate) {
    this.forexRate = forexRate;
  }

  public StatementEntry additionalFields(Map<String, String> additionalFields) {
    this.additionalFields = additionalFields;
    return this;
  }

  public StatementEntry putAdditionalFieldsItem(String key, String additionalFieldsItem) {
    if (this.additionalFields == null) {
      this.additionalFields = new HashMap<>();
    }
    this.additionalFields.put(key, additionalFieldsItem);
    return this;
  }

   /**
   * A Map of additional fields related to the transaction, containing for example fee information.
   * @return additionalFields
  **/
  public Map<String, String> getAdditionalFields() {
    return additionalFields;
  }

  public void setAdditionalFields(Map<String, String> additionalFields) {
    this.additionalFields = additionalFields;
  }

  public StatementEntry cardholderFee(CurrencyAmount cardholderFee) {
    this.cardholderFee = cardholderFee;
    return this;
  }

   /**
   * Get cardholderFee
   * @return cardholderFee
  **/
  public CurrencyAmount getCardholderFee() {
    return cardholderFee;
  }

  public void setCardholderFee(CurrencyAmount cardholderFee) {
    this.cardholderFee = cardholderFee;
  }

  public StatementEntry transactionAmount(CurrencyAmount transactionAmount) {
    this.transactionAmount = transactionAmount;
    return this;
  }

   /**
   * Get transactionAmount
   * @return transactionAmount
  **/
  public CurrencyAmount getTransactionAmount() {
    return transactionAmount;
  }

  public void setTransactionAmount(CurrencyAmount transactionAmount) {
    this.transactionAmount = transactionAmount;
  }

  public StatementEntry processedTimestamp(Long processedTimestamp) {
    this.processedTimestamp = processedTimestamp;
    return this;
  }

   /**
   * The timestamp when the transaction was processed by the system, expressed in Epoch timestamp using millisecond precision.
   * @return processedTimestamp
  **/
  public Long getProcessedTimestamp() {
    return processedTimestamp;
  }

  public void setProcessedTimestamp(Long processedTimestamp) {
    this.processedTimestamp = processedTimestamp;
  }

  public StatementEntry balanceAfter(CurrencyAmount balanceAfter) {
    this.balanceAfter = balanceAfter;
    return this;
  }

   /**
   * Get balanceAfter
   * @return balanceAfter
  **/
  public CurrencyAmount getBalanceAfter() {
    return balanceAfter;
  }

  public void setBalanceAfter(CurrencyAmount balanceAfter) {
    this.balanceAfter = balanceAfter;
  }

  public StatementEntry sourceAmount(Object sourceAmount) {
    this.sourceAmount = sourceAmount;
    return this;
  }

   /**
   * Get sourceAmount
   * @return sourceAmount
  **/
  public Object getSourceAmount() {
    return sourceAmount;
  }

  public void setSourceAmount(Object sourceAmount) {
    this.sourceAmount = sourceAmount;
  }

  public StatementEntry transactionId(TransactionId transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  public TransactionId getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(TransactionId transactionId) {
    this.transactionId = transactionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatementEntry StatementEntry = (StatementEntry) o;
    return Objects.equals(this.originalAmount, StatementEntry.originalAmount) &&
        Objects.equals(this.forexRate, StatementEntry.forexRate) &&
        Objects.equals(this.additionalFields, StatementEntry.additionalFields) &&
        Objects.equals(this.cardholderFee, StatementEntry.cardholderFee) &&
        Objects.equals(this.transactionAmount, StatementEntry.transactionAmount) &&
        Objects.equals(this.processedTimestamp, StatementEntry.processedTimestamp) &&
        Objects.equals(this.balanceAfter, StatementEntry.balanceAfter) &&
        Objects.equals(this.sourceAmount, StatementEntry.sourceAmount) &&
        Objects.equals(this.transactionId, StatementEntry.transactionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalAmount, forexRate, additionalFields, cardholderFee, transactionAmount, processedTimestamp, balanceAfter, sourceAmount, transactionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatementEntry {\n");
    
    sb.append("    originalAmount: ").append(toIndentedString(originalAmount)).append("\n");
    sb.append("    forexRate: ").append(toIndentedString(forexRate)).append("\n");
    sb.append("    additionalFields: ").append(toIndentedString(additionalFields)).append("\n");
    sb.append("    cardholderFee: ").append(toIndentedString(cardholderFee)).append("\n");
    sb.append("    transactionAmount: ").append(toIndentedString(transactionAmount)).append("\n");
    sb.append("    processedTimestamp: ").append(toIndentedString(processedTimestamp)).append("\n");
    sb.append("    balanceAfter: ").append(toIndentedString(balanceAfter)).append("\n");
    sb.append("    sourceAmount: ").append(toIndentedString(sourceAmount)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
