/*
 * Weavr Multi Product API
 * Weavr Multi API provides a simple and flexible way to issue cards and accounts to your customers.  By integrating Weavr Multi API in your application you can embed banking capabilities within your app and provide a seamless experience for our customers.   # Authentication Each request to the Multi API needs to be signed with an `api_key` that represents your account. You can obtain an API Key by registering for a Multi account [here](https://portal.weavr.io).  Almost all endpoints require a secondary authentication token `Authorization` that represents the user for whom the request is being executed.   <!-- ReDoc-Inject: <security-definitions> --> 
 *
 * OpenAPI spec version: 3.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.weavrbank.weavrLogin.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * VerificationMobileResponse
 */

public class VerificationMobileResponse {
  @JsonProperty("retriesLeft")
  private Integer retriesLeft = null;

  @JsonProperty("timeLeftForRetry")
  private Long timeLeftForRetry = null;

  public VerificationMobileResponse retriesLeft(Integer retriesLeft) {
    this.retriesLeft = retriesLeft;
    return this;
  }

   /**
   * The number of retries left.
   * @return retriesLeft
  **/
  public Integer getRetriesLeft() {
    return retriesLeft;
  }

  public void setRetriesLeft(Integer retriesLeft) {
    this.retriesLeft = retriesLeft;
  }

  public VerificationMobileResponse timeLeftForRetry(Long timeLeftForRetry) {
    this.timeLeftForRetry = timeLeftForRetry;
    return this;
  }

   /**
   * Timestamp after which another verification code can be sent, expressed in Epoch timestamp using millisecond precision.
   * @return timeLeftForRetry
  **/
  public Long getTimeLeftForRetry() {
    return timeLeftForRetry;
  }

  public void setTimeLeftForRetry(Long timeLeftForRetry) {
    this.timeLeftForRetry = timeLeftForRetry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerificationMobileResponse VerificationMobileResponse = (VerificationMobileResponse) o;
    return Objects.equals(this.retriesLeft, VerificationMobileResponse.retriesLeft) &&
        Objects.equals(this.timeLeftForRetry, VerificationMobileResponse.timeLeftForRetry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retriesLeft, timeLeftForRetry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerificationMobileResponse {\n");
    
    sb.append("    retriesLeft: ").append(toIndentedString(retriesLeft)).append("\n");
    sb.append("    timeLeftForRetry: ").append(toIndentedString(timeLeftForRetry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
