package com.weavrbank.weavrLogin.service;


import com.weavrbank.weavrLogin.model.*;
import com.weavrbank.weavrLogin.model.Error;
import com.weavrbank.weavrLogin.model.InlineResponse2007;
import com.weavrbank.weavrLogin.model.InlineResponse40912;
import com.weavrbank.weavrLogin.model.Transfer;
import com.weavrbank.weavrLogin.model.TransfersBody;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.lang.Object;
import org.springframework.util.MultiValueMap;
import feign.*;

public interface TransfersService {

  /**
   * Create transfer transaction
   * Transfers funds between managed accounts and managed cards belonging to the same corporate or consumer identity.  The Transfer Profile (configured in the Multi Portal) specified determines the behaviour and restrictions of the transaction (for example, fees). 
    * @param body  (required)
    * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
   * @return Transfer
   */
  @RequestLine("POST /transfers")
  @Headers({
    "Content-Type: application/json",
    "Accept: application/json",
    "idempotency-ref: {idempotency_ref}"  })
  Transfer transferCreate(TransfersBody body, @Param("idempotency_ref") String idempotency_ref);

  /**
   * Get transfer transaction
   * Retrieve the transfer transaction identified by the &#x60;id&#x60; path parameter.
    * @param id The unique identifier of the Transfer transaction. (required)
    * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
   * @return Transfer
   */
  @RequestLine("GET /transfers/{id}")
  @Headers({
    "Accept: application/json",
    "idempotency-ref: {idempotency_ref}"  })
  Transfer transferGet(@Param("id") String id, @Param("idempotency_ref") String idempotency_ref);

  /**
   * Get transfer transactions
   * Retrieves all the transfer transactions performed by the logged-in identity.
    * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
    * @param paging The offset and number of results to return. Leave out to fetch the first page of results. (optional)
    * @param profileId Filter by the transfer profile. Leave out to fetch all transfer transactions. (optional)
    * @param instrumentId Filter by the source instrument id. (optional)
    * @param state Filter by the transfer transaction state. Leave out to fetch all states. (optional)
    * @param createdFrom Filter for transfer transactions created after &#x60;createdFrom&#x60; timestamp. Timestamp is expressed in Epoch timestamp using millisecond precision. Leave out to fetch all transfers. (optional)
    * @param createdTo Filter for transfer transactions created before &#x60;createdTo&#x60; timestamp. Timestamp is expressed in Epoch timestamp using millisecond precision. Leave out to fetch all transfers. (optional)
    * @param tag Filter by the transfer tag. The exact tag must be provided, as wildcards are not supported. Leave out to fetch all entries. (optional)
   * @return InlineResponse2007
   */
  @RequestLine("GET /transfers?paging={paging}&profileId={profileId}&instrumentId={instrumentId}&state={state}&createdFrom={createdFrom}&createdTo={createdTo}&tag={tag}")
  @Headers({
    "Accept: application/json",
    "idempotency-ref: {idempotency_ref}"  })
  InlineResponse2007 transfersGet(@Param("idempotency_ref") String idempotency_ref, @Param("paging") Object paging, @Param("profileId") String profileId, @Param("instrumentId") Object instrumentId, @Param("state") List state, @Param("createdFrom") Long createdFrom, @Param("createdTo") Long createdTo, @Param("tag") String tag);


    /**
     * Get transfer transactions
     * Retrieves all the transfer transactions performed by the logged-in identity.
     * Note, this is equivalent to the other <code>transfersGet</code> method,
     * but with the query parameters collected into a single Map parameter. This
     * is convenient for services with optional query parameters, especially when
     * used with the {@link TransfersGetQueryParams} class that allows for
     * building up this map in a fluent style.
     * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
     * @param queryParams Map of query parameters as name-value pairs
     *   <p>The following elements may be specified in the query map:</p>
     *   <ul>
     *   <li>paging - The offset and number of results to return. Leave out to fetch the first page of results. (optional)</li>
     *   <li>profileId - Filter by the transfer profile. Leave out to fetch all transfer transactions. (optional)</li>
     *   <li>instrumentId - Filter by the source instrument id. (optional)</li>
     *   <li>state - Filter by the transfer transaction state. Leave out to fetch all states. (optional)</li>
     *   <li>createdFrom - Filter for transfer transactions created after &#x60;createdFrom&#x60; timestamp. Timestamp is expressed in Epoch timestamp using millisecond precision. Leave out to fetch all transfers. (optional)</li>
     *   <li>createdTo - Filter for transfer transactions created before &#x60;createdTo&#x60; timestamp. Timestamp is expressed in Epoch timestamp using millisecond precision. Leave out to fetch all transfers. (optional)</li>
     *   <li>tag - Filter by the transfer tag. The exact tag must be provided, as wildcards are not supported. Leave out to fetch all entries. (optional)</li>
     *   </ul>
     * @return InlineResponse2007
     */
    @RequestLine("GET /transfers?paging={paging}&profileId={profileId}&instrumentId={instrumentId}&state={state}&createdFrom={createdFrom}&createdTo={createdTo}&tag={tag}")
    @Headers({
    "Accept: application/json",
        "idempotency-ref: {idempotency_ref}"    })
    InlineResponse2007 transfersGet
    (@Param("idempotency_ref") String idempotency_ref, @QueryMap(encoded=true)
    MultiValueMap<String, String> queryParams);

}
