package com.weavrbank.weavrLogin.service;


import com.weavrbank.weavrLogin.model.*;
import com.weavrbank.weavrLogin.model.Error;
import com.weavrbank.weavrLogin.model.InlineResponse2009;
import com.weavrbank.weavrLogin.model.InlineResponse40927;
import com.weavrbank.weavrLogin.model.LoginWithPasswordBody;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.lang.Object;
import org.springframework.util.MultiValueMap;
import feign.*;

public interface UserAuthenticationService {

  /**
   * Login with password
   * Authenticate a user with the &#x60;email&#x60; and &#x60;password&#x60; that they provided when registering.  Given that the user credentials are correct, this returns a &#x60;token&#x60; that can then be used to authorise other secured operations. In case the password is expired, a temporary &#x60;token&#x60; is returned, which can be used solely for updating the password. 
    * @param body  (required)
    * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
   * @return InlineResponse2009
   */
  @RequestLine("POST /login_with_password")
  @Headers({
    "Content-Type: application/json",
    "Accept: application/json",
    "idempotency-ref: {idempotency_ref}"  })
  InlineResponse2009 loginWithPassword(LoginWithPasswordBody body, @Param("idempotency_ref") String idempotency_ref);

  /**
   * Logout
   * Logs out the user and terminates the session identified by the &#x60;Authorization&#x60; in the Authorization Header.
    * @param idempotency_ref A unique call reference generated by the caller that, taking into consideration the payload as well as the operation itself, helps avoid duplicate operations.  Idempotency reference uniqueness is maintained for at least 24 hours. (optional)
   */
  @RequestLine("POST /logout")
  @Headers({
    "Content-Type: application/json",
    "Accept: application/json",
    "idempotency-ref: {idempotency_ref}"  })
  void logout(@Param("idempotency_ref") String idempotency_ref);

}
